forum_module_legacy_redirect:
    resource: ../../Controller/LegacyForumRedirectController.php
    type: attribute

forum_module_front:
    resource: ../../Controller/
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '%cpalius.locales_pattern%'
    defaults:
        _locale: '%cpalius.default_locale%'
    exclude:
        - ../../Controller/Admin/
        - ../../Controller/LegacyForumRedirectController.php

forum_module_admin:
    resource: ../../Controller/Admin/
    type: attribute
