<?php

declare(strict_types=1);

namespace App\Core\Font;

use App\Core\Settings\SettingsRegistry;

/**
 * Writes public/fonts/fonts.css: the @font-face blocks for every installed
 * family, then the role assignments on :root.
 *
 * A generated file rather than a per-request render, because this is the same
 * bytes for every visitor and belongs in front of the PHP process, not behind
 * it. It is rebuilt when a font is installed or removed and when the
 * assignments are saved — the three moments its content can change.
 *
 * The role assignments are only custom-property definitions. The theme reads
 * those properties everywhere it sets a typeface, so redefining them here beats
 * the theme on cascade order (this file is linked after it) without a single
 * !important and without this class knowing one theme selector.
 */
final class FontStylesheetBuilder
{
    public const FILE = 'fonts.css';

    public function __construct(
        private readonly FontLibrary $library,
        private readonly SettingsRegistry $settings,
    ) {
    }

    public function publicPath(): string
    {
        return FontLibrary::PUBLIC_PREFIX.'/'.self::FILE;
    }

    public function filePath(): string
    {
        return $this->library->rootPath().'/'.self::FILE;
    }

    public function exists(): bool
    {
        return is_file($this->filePath());
    }

    /**
     * @return bool whether the file is now on disk
     */
    public function rebuild(): bool
    {
        $families = $this->library->families();
        $assignments = $this->assignments();

        // Nothing installed and nothing assigned: remove the file rather than
        // leave an empty stylesheet the layout still has to fetch.
        if ($families === [] && $assignments === []) {
            if ($this->exists()) {
                @unlink($this->filePath());
            }

            return false;
        }

        $this->library->ensureRoot();

        return @file_put_contents($this->filePath(), $this->render($families, $assignments)) !== false;
    }

    /**
     * @param list<FontFamily>      $families
     * @param array<string, string> $assignments role => family slug
     */
    public function render(array $families, array $assignments): string
    {
        $out = "/* Generated by CPalius — AACP → Appearance → Fonts. Edits are overwritten. */\n";

        foreach ($families as $family) {
            foreach ($family->faces as $face) {
                $out .= "@font-face{font-family:".$family->cssName().";";
                $out .= "src:url('".$face->url."') format('".$face->format."');";
                $out .= "font-weight:".$face->weight.";font-style:".$face->style.";font-display:swap;";
                if ($face->unicodeRange !== null && $face->unicodeRange !== '') {
                    $out .= "unicode-range:".$face->unicodeRange.";";
                }
                $out .= "}\n";
            }
        }

        $byRole = [];
        foreach ($assignments as $role => $slug) {
            $stack = $this->stackFor($slug, $role, $families);
            if ($stack !== null) {
                $byRole[$role] = $stack;
            }
        }

        $rootLines = [];
        foreach (FontRole::variableRoles() as $role => $property) {
            if (isset($byRole[$role])) {
                $rootLines[] = $property.':'.$byRole[$role];
            }
        }

        if ($rootLines !== []) {
            $out .= ":root{".implode(';', $rootLines).";}\n";
        }

        // Per-heading overrides redefine the heading variable ON the element
        // rather than setting font-family. Custom properties inherit, and the
        // theme's own rule is already "font-family: var(--cp-font-heading)", so
        // this wins whatever that rule's specificity is — setting font-family
        // here would lose to any themed selector carrying a class.
        $headingVariable = FontRole::variableRoles()[FontRole::HEADING];

        foreach (FontRole::selectorRoles() as $role => $selector) {
            if (isset($byRole[$role])) {
                $out .= $selector.'{'.$headingVariable.':'.$byRole[$role].";}\n";
            }
        }

        return $out;
    }

    /**
     * @return array<string, string> role => chosen value, only the roles that have one
     */
    public function assignments(): array
    {
        $out = [];

        foreach (FontRole::all() as $role) {
            $value = trim((string) $this->settings->get(FontRole::settingKey($role), ''));

            if ($value !== '') {
                $out[$role] = $value;
            }
        }

        return $out;
    }

    /**
     * Resolves a stored value to a full font stack.
     *
     * The value is either the slug of an installed family or one of the
     * web-safe stacks, which are offered because a site does not have to ship a
     * font file to choose Georgia — the visitor already has it.
     *
     * @param list<FontFamily> $families
     */
    private function stackFor(string $value, string $role, array $families): ?string
    {
        foreach ($families as $family) {
            if ($family->slug === $value) {
                return $family->cssName().', '.FontRole::fallbackFor($role);
            }
        }

        $stack = FontStack::system($value);

        return $stack;
    }
}
