<?php

declare(strict_types=1);

namespace App\Core\Config;

use Symfony\Component\Yaml\Yaml;

/**
 * Deterministic YAML read/write for the config sync directory. Keys are sorted
 * recursively so two environments with equal config produce byte-identical files.
 */
final class ConfigFile
{
    private const HEADER = "# CPalius config sync — generated by cp:config:export. Edit in Git, apply with cp:config:import.\n";

    public function __construct(
        private readonly string $syncDir,
    ) {
    }

    public function path(string $name): string
    {
        return $this->syncDir.'/'.$name.'.yaml';
    }

    public function exists(string $name): bool
    {
        return is_file($this->path($name));
    }

    /**
     * @return list<string> document names present on disk (recursively; "workflow/x" style kept)
     */
    public function listOnDisk(): array
    {
        if (!is_dir($this->syncDir)) {
            return [];
        }

        $names = [];
        $iterator = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($this->syncDir, \FilesystemIterator::SKIP_DOTS),
        );
        foreach ($iterator as $file) {
            if ($file->getExtension() === 'yaml') {
                $names[] = str_replace('\\', '/', substr(
                    (string) $file->getPathname(),
                    \strlen($this->syncDir) + 1,
                    -5,
                ));
            }
        }
        sort($names);

        return $names;
    }

    /**
     * @return array<string, mixed>
     */
    public function read(string $name): array
    {
        $path = $this->path($name);
        if (!is_file($path)) {
            return [];
        }

        try {
            $data = Yaml::parseFile($path);
        } catch (\Throwable) {
            return [];
        }

        return \is_array($data) ? $data : [];
    }

    /**
     * @param array<string, mixed> $data
     */
    public function write(string $name, array $data): void
    {
        $path = $this->path($name);
        $dir = \dirname($path);
        if (!is_dir($dir)) {
            @mkdir($dir, 0o775, true);
        }

        $body = self::HEADER.Yaml::dump($this->sortRecursive($data), 6, 2, Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK);

        // Atomic write.
        $tmp = $path.'.tmp';
        file_put_contents($tmp, $body, \LOCK_EX);
        rename($tmp, $path);
    }

    public function delete(string $name): void
    {
        $path = $this->path($name);
        if (is_file($path)) {
            @unlink($path);
        }
    }

    /**
     * @param array<mixed> $value
     *
     * @return array<mixed>
     */
    private function sortRecursive(array $value): array
    {
        $isList = array_is_list($value);
        foreach ($value as $k => $v) {
            if (\is_array($v)) {
                $value[$k] = $this->sortRecursive($v);
            }
        }
        if (!$isList) {
            ksort($value);
        }

        return $value;
    }
}
